### ISSUE TITLE
Commento al README

### ISSUE THREAD

**Issue by iannellog** [PaoloRuggirello/bingo-core#1]
Sono riuscito a installare il tutto, ma ho notato una piccola cosa nel README:
al passo 4 c'è scritto "move in the 'docker-general' folder", in realtà il folder si chiama "bingo-docker"; non so se c'è un motivo, ma perché non mettere il nome vero del fonder? questa incongruenza mi ha inizialmente confuso.

Converrebbe anche indicare come stoppare il server (io ho semplicemente usato crtl-c, non so se c'è un modo più intelligente) e aggiungere che per far ripartire il gioco basta ridigitare 'docker-compose up' (non darei per scontato che l'utente conosca il comando docker-compose). Poi leggendo il punto 4 sembra che che questo comando serva a generare qualcosa, e non è immediatamente chiaro che invece serve ad avviare i due container e (solo) la prima volta deve generare delle cose.

**Comment by iannellog** [comment]
Ho cominciato a guardare il codice. Premesso che mi sembra abbiate fatto un ottimo lavoro, sarebbe utile inserire commenti che descrivano sinteticamente cosa contengono i file nella directory bingo-core/bingo. Per esempio, non riesco a capire a che servono i file NPArray, DBList, DictInDB.
Anche un diagramma delle classi sarebbe utile.

**Comment by PaoloRuggirello** [comment]
- al passo 4 c'è scritto "move in the 'docker-general' folder", in realtà il folder si chiama "bingo-docker" -  Ha ragione, la cartella inizialmente di chiamava in quel modo, ho dimenticato ad aggiornare la documentazione.
Ho corretto il punto 4

**Comment by PaoloRuggirello** [comment]
Il readme file è stato aggiornato

**Comment by PaoloRuggirello** [comment]
Commenti alle classi aggiunti

**Comment by PaoloRuggirello** [comment]
Diagramma delle classi creato, chiudo la issue
