### ISSUE TITLE
Errore nei comandi di installazione

### ISSUE THREAD

**Issue by iannellog** [PaoloRuggirello/bingo-core#2]
Quando si genera la libreria viene creata la cartella bingo-be/dist-util che contiene il file .tar.gz, ma la procedura di generazione delle imagini Docker richiede che il file sia nella directory bingo-be/dist_util (con '_' e non '-') per cui si genera un errore.

**Comment by PaoloRuggirello** [comment]
Grazie per la segnalazione, il bug è stato corretto
