### ISSUE TITLE
Suggerimenti per migliorare documentazione

### ISSUE THREAD

**Issue by iannellog** [PaoloRuggirello/bingo-core#3]
Suggerisco di inserire all'inizio dei file Python nella cartella bingo-core/bingo un commento che illustri il ruolo del file nell'organizzazione complessiva del codice (per es. quali classi, che servizi offrono agli altri file). 
Sarebbe anche utile un diagramma delle classi e delle istanze.
Potete limitarvi a farlo per bingo-core (cioè l'applicazione che gira da linea di comando).

**Comment by PaoloRuggirello** [comment]
Abbiamo fornito la documentazione richiesta all'interno della cartella docs
